Add NGINX_MODE environment variable

diff --git a/install/etc/cont-init.d/09-nginx b/install/etc/cont-init.d/09-nginx
--- a/install/etc/cont-init.d/09-nginx
+++ b/install/etc/cont-init.d/09-nginx
@@ -56,6 +56,7 @@ NGINX_LOG_ACCESS_LOCATION=${NGINX_LOG_ACCESS_LOCATION:-"/www/logs/nginx"}
 NGINX_LOG_ERROR_FILE=${NGINX_LOG_ERROR_FILE:-"error.log"}
 NGINX_LOG_ERROR_LOCATION=${NGINX_LOG_ERROR_LOCATION:-"/www/logs/nginx"}
 NGINX_LOG_LEVEL_ERROR=${NGINX_LOG_LEVEL_ERROR:-"warn"}
+NGINX_MODE=${NGINX_MODE:-"NORMAL"}
 NGINX_OPEN_FILE_CACHE_ERRORS=${NGINX_OPEN_FILE_CACHE_ERRORS:-"on"}
 NGINX_OPEN_FILE_CACHE_INACTIVE=${NGINX_OPEN_FILE_CACHE_INACTIVE:-"5m"}
 NGINX_OPEN_FILE_CACHE_MAX=${NGINX_OPEN_FILE_CACHE_MAX:-200000}
@@ -175,6 +176,34 @@ if [ "$ENABLE_ZABBIX" != "TRUE" ]; then
   sed -i -e "\#include /etc/nginx/nginx.conf.d/zabbix.conf;#d" /etc/nginx/nginx.conf
 fi
 
+case "$NGINX_MODE" in
+  "MAINTENANCE")
+    echo "** [nginx] MAINTENANCE MODE ACTIVATED - THIS IMAGE WILL NOT SERVE PAGES"
+    mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.template
+    mv /etc/nginx/conf.d/maintenance.template /etc/nginx.conf.d/maintenance.conf
+  ;;
+  "NORMAL")
+    :
+  ;;
+  "REDIRECT")
+    if [ ! -n "$NGINX_REDIRECT_URL" ]; then
+      echo '** [nginx] ERROR: No NGINX_REDIRECT_URL Set!'
+      exit 1
+    fi
+    
+    NGINX_ENABLE_CREATE_SAMPLE_HTML=FALSE
+
+    sed -i "s#rewrite \^/(\.\*) .*#rewrite ^/(\.\*) ${NGINX_REDIRECT_URL};#g" /etc/nginx/conf.d/redirect.template 
+
+    echo "** [nginx] Redirect Mode Activated - Redirecting all traffic to ${NGINX_REDIRECT_URL}"
+    mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.template
+    mv /etc/nginx/conf.d/redirect.template /etc/nginx/conf.d/redirect.conf
+  ;;
+  *)
+    :
+  ;;
+esac
+
 if [ "$NGINX_ENABLE_APPLICATION_CONFIGURATION" = "TRUE" ]; then
 ## Configure default.conf
   ### Map Authentication
@@ -188,7 +217,7 @@ if [ "$NGINX_ENABLE_APPLICATION_CONFIGURATION" = "TRUE" ]; then
             basic_pass=NGINX_AUTHENTICATION_BASIC$_PASS{i}
             echo "** [nginx] Creating User: ${!basic_user}"
             htpasswd -b -n ${!basic_user:-$NGINX_AUTHENTICATION_BASIC_USER} ${!basic_pass:-$NGINX_AUTHENTICATION_BASIC_PASS} >> /etc/nginx/nginx.conf.d/authentication/basic_authorized_users
-            sed -i '/ server {/a\ \ \  auth_basic "${NGINX_AUTHENTICATION_TITLE}"; auth_basic_user_file /etc/nginx/nginx.conf.d/authentication/basic_authorized_users;' /etc/nginx/conf.d/default.conf
+            sed -i '/ server {/a\ \ \  auth_basic "${NGINX_AUTHENTICATION_TITLE}"; auth_basic_user_file /etc/nginx/nginx.conf.d/authentication/basic_authorized_users;' /etc/nginx/conf.d/*.conf
           done
       ;;
       "LDAP")
@@ -203,7 +232,7 @@ if [ "$NGINX_ENABLE_APPLICATION_CONFIGURATION" = "TRUE" ]; then
         satisfy all;
       }
 EOF
-        sed -i '/ server {/a\ \ \  auth_ldap "${NGINX_AUTHENTICATION_TITLE}"; auth_ldap_servers ldapserver;' /etc/nginx/conf.d/default.conf
+        sed -i '/ server {/a\ \ \  auth_ldap "${NGINX_AUTHENTICATION_TITLE}"; auth_ldap_servers ldapserver;' /etc/nginx/conf.d/*.conf
         sed -i "\#include /etc/nginx/conf.d/#i\ \ \ \ include /etc/nginx/nginx.conf.d/authentication/ldap_configuration;" /etc/nginx/nginx.conf
       ;;
       "LLNG")
@@ -223,8 +252,8 @@ EOF
                   echo "auth_request_set \$${array[1]} \$${array[2]};" >> /etc/nginx/nginx.conf.d/authentication/llng_auth_request
             done
 
-          sed -i '/ server {/a\ \ \ \ \  include /etc/nginx/nginx.conf.d/authentication/llng;' /etc/nginx/conf.d/default.conf
-          sed -i '/ location \/ {/a\ \ \ \ \ \ \ \ include /etc/nginx/nginx.conf.d/authentication/llng_auth_request;' /etc/nginx/conf.d/default.conf
+          sed -i '/ server {/a\ \ \ \ \  include /etc/nginx/nginx.conf.d/authentication/llng;' /etc/nginx/conf.d/*.conf
+          sed -i '/ location \/ {/a\ \ \ \ \ \ \ \ include /etc/nginx/nginx.conf.d/authentication/llng_auth_request;' /etc/nginx/conf.d/*.conf
       ;;
       "NONE")
         :
@@ -235,16 +264,13 @@ EOF
   esac
 
   sed -i -e "s#<WEBROOT>#${NGINX_WEBROOT}#g" /etc/nginx/conf.d/*.conf > /dev/null
-  sed -i -e "s#<LISTEN_PORT>#${NGINX_LISTEN_PORT}#g" /etc/nginx/conf.d/* > /dev/null
+  sed -i -e "s#<LISTEN_PORT>#${NGINX_LISTEN_PORT}#g" /etc/nginx/conf.d/*.conf > /dev/null
+  sed -i -e "s#<WEBROOT>#${NGINX_WEBROOT}#g" /etc/nginx/conf.d/*.template > /dev/null
+  sed -i -e "s#<LISTEN_PORT>#${NGINX_LISTEN_PORT}#g" /etc/nginx/conf.d/*.template > /dev/null
 else 
   echo "** [nginx] Not configurating application / default.conf files"
 fi
 
-if [ "$MAINTENANCE" = "TRUE" ] || [ "$MAINTENANCE" = "true" ];  then
-  echo "** MAINTENANCE MODE ACTIVATED - THIS IMAGE WILL NOT SERVE PAGES"
-  mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.orig
-  mv /etc/nginx/conf.d/maintenance.conf.maint /etc/nginx.conf.d/maintenance.conf
-fi
 
 ### Set Stage for Future Development and Production Purposes
 case "$STAGE" in
@@ -276,7 +302,7 @@ fi
 
 ### Force Reset Permissions for Accessibility
 mkdir -p ${NGINX_WEBROOT}
-chown -R nginx:www-wwwdata ${NGINX_WEBROOT}
+chown -R nginx ${NGINX_WEBROOT}
 
 ### Create Log Directories
 mkdir -p ${NGINX_LOG_ERROR_LOCATION} ${NGINX_LOG_ACCESS_LOCATION}
